// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqwfeukmqhypbqihbdtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xd2ZldWttcWh5cGJxaWhiZHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODA1NDcsImV4cCI6MjA2NzY1NjU0N30.3K4FB2OeJbLziNXCUtIXqzRKY1F7Jaf3bPW6lG2FkQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});